name: CI Pipeline

on:
  push:
    branches:
      - api-feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run CI build script
      run: echo "CI Build Passed"
